// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPort(arg1, arg2) {
  return window['go']['main']['App']['CheckPort'](arg1, arg2);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function ExportReport(arg1) {
  return window['go']['main']['App']['ExportReport'](arg1);
}

export function FlushDNS() {
  return window['go']['main']['App']['FlushDNS']();
}

export function GetFirewallStatus() {
  return window['go']['main']['App']['GetFirewallStatus']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ReleaseRenewIP() {
  return window['go']['main']['App']['ReleaseRenewIP']();
}

export function RequestElevation() {
  return window['go']['main']['App']['RequestElevation']();
}

export function ResetNetworkStack() {
  return window['go']['main']['App']['ResetNetworkStack']();
}

export function RestartNetworkServices() {
  return window['go']['main']['App']['RestartNetworkServices']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RunComprehensiveRepair() {
  return window['go']['main']['App']['RunComprehensiveRepair']();
}

export function RunDiagnostic() {
  return window['go']['main']['App']['RunDiagnostic']();
}

export function RunPing(arg1) {
  return window['go']['main']['App']['RunPing'](arg1);
}

export function RunRepair(arg1) {
  return window['go']['main']['App']['RunRepair'](arg1);
}

export function RunSingleDiagnostic(arg1) {
  return window['go']['main']['App']['RunSingleDiagnostic'](arg1);
}

export function RunTraceroute(arg1) {
  return window['go']['main']['App']['RunTraceroute'](arg1);
}

export function SwitchDNS(arg1, arg2) {
  return window['go']['main']['App']['SwitchDNS'](arg1, arg2);
}
