// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {types} from '../models';

export function CheckPort(arg1:string,arg2:string):Promise<string>;

export function CreateBackup():Promise<string>;

export function ExportReport(arg1:string):Promise<string>;

export function FlushDNS():Promise<void>;

export function GetFirewallStatus():Promise<string>;

export function GetNetworkInfo():Promise<string>;

export function IsAdmin():Promise<boolean>;

export function ListBackups():Promise<Array<backup.BackupInfo>>;

export function ReleaseRenewIP():Promise<void>;

export function RequestElevation():Promise<void>;

export function ResetNetworkStack():Promise<void>;

export function RestartNetworkServices():Promise<string>;

export function RestoreBackup(arg1:string):Promise<void>;

export function RunComprehensiveRepair():Promise<Array<types.RepairResult>>;

export function RunDiagnostic():Promise<Array<types.DiagnosticResult>>;

export function RunPing(arg1:string):Promise<string>;

export function RunRepair(arg1:string):Promise<types.RepairResult>;

export function RunSingleDiagnostic(arg1:string):Promise<types.DiagnosticResult>;

export function RunTraceroute(arg1:string):Promise<string>;

export function SwitchDNS(arg1:string,arg2:string):Promise<boolean>;
